services:
  pageweb:
    container_name: web-pageweb
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    ports:
      - 80:80
    networks: 
    - student-list-networks
    depends_on:
      - api
    volumes:
      - ./website:/var/www/html


  api:
    container_name: api
    image: api:v1.0
    #ports:
    #  - 5000
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - student-list-networks

networks :
    student-list-networks :
      driver: bridge
      name: student-list-networks